### ISSUE TITLE
Localizations not being pruned for some pods

### ISSUE THREAD

**Issue by tapi** [dtorres/cocoapods-prune-localizations#3]
We're using [FormatterKit](https://github.com/mattt/FormatterKit) and were hoping to use this plugin to get rid of some of the extra localizations but it isn't working in the case of this pod.

After digging around in the source my suspicion is that this has to do with the localizations being specified in subspecs or being mapped to a folder other than Resources but my ruby is terrible so I may be completely wrong.

**Comment by dtorres** [comment]
You are right, this is because this Pod uses a custom group organization.
I'll do a more generic approach for it

**Comment by dtorres** [comment]
I've just published cocoapods-prune-localizations 0.1.1. This fixes your issue.

**Comment by tapi** [comment]
👍🏻🎉

**Comment by tapi** [comment]
Confirmed this morning that it works, thanks for the plugin and the fix!
