### ISSUE TITLE
"Pods/Pruned Localized Bundles" bundle files not correctly re-added to project

### ISSUE THREAD

**Issue by glentregoning** [dtorres/cocoapods-prune-localizations#7]
I've recently enabled use_frameworks! in my Podfile and now notice that the bundles file aren't correctly added to the Pods project.

This can be reproduced by setting up a project with use_frameworks! that includes the https://github.com/MatthewYork/DateTools/ pod, and observing that when you build the project the Bundle isn't included in the built product.

**Comment by dtorres** [comment]
Closing as fixed by #8
